# Generated by Django 3.1.3 on 2020-11-25 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='leader',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='users.boss'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='users.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='projects', through='users.Employee', to='users.Boss'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('T', 'Thainee'), ('J', 'Jinior'), ('M', 'Middle'), ('S', 'Senior')], default='T', max_length=1),
        ),
    ]
