# Generated by Django 3.1.3 on 2020-11-25 14:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='non-slug', editable=False, populate_from='user__username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boss',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user__username'),
        ),
    ]
