# Generated by Django 3.1.3 on 2020-11-26 11:30

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201125_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='slug-none', editable=False, populate_from='username'),
            preserve_default=False,
        ),
    ]
