# Generated by Django 3.1.3 on 2020-12-08 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201129_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='projects', to='users.Boss', verbose_name='Руководители проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='heads',
            field=models.ManyToManyField(blank=True, related_name='projects', to='users.Boss', verbose_name='Руководители проекта'),
        )
    ]